repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.30.1
    hooks:
      - id: typos
        args: []
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
