/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    'intro',
    // {
    //   type: 'html',
    //   value: 'website/static/projects'
    // },
    {
      type: 'category',
      label: 'Reading List',
      link:{
        type: 'doc',
        id: 'reading-list/index',
      },
      items: [
        'reading-list/git',
        'reading-list/tips-tricks',
      ],
    },
    {
      type: 'category',
      label: 'Shell',
      link: {
        type: 'generated-index',
      },
      items: [
        'shell/bash-wiki',
        'shell/rsync-wiki',
        'shell/sed-wiki',
        'how-tos/identify-git-outdated-files',
      ],
    },
    'git-wiki',
    {
      type: 'category',
      label: 'Python',
      // Use link to generate index page for each category
      link: {
        type: 'generated-index',
      },
      items: [
        'how-tos/python-test-shell-scripts',
        'python/time-in-python',
        'how-tos/manage-python-project-using-poetry',
        {
          type: 'category',
          label: 'Applied data science',
          link: {
            type: 'generated-index',
          },
          items:[
            'placeholder',
          ]
        },
        {
          type: 'category',
          label: 'Understanding and visualizing data',
          link: {
            type: 'generated-index',
          },
          items:[
            'placeholder',
          ]
        }
      ],
    },
    {
      type: 'category',
      label: 'Hadoop',
      link: {
        type: 'generated-index',
      },
      items: [
        'hadoop/hadoop-01-introduction',
        'hadoop/hadoop-02-about-mapreduce',
        'hadoop/hadoop-03-install-step-by-step'
      ],
    },
    {
      type: 'category',
      label: 'Game Theory',
      link: {
        type: 'generated-index',
      },
      items: [
        'placeholder'
      ],
    },
    {
      type: 'category',
      label: 'Docker',
      link: {
        type: 'generated-index',
      },
      items: [
        { type: 'ref', id: 'placeholder' }
      ],
    },
    {
      type: 'category',
      label: 'How-Tos',
      link: {
        type: 'generated-index',
      },
      items: [
        'how-tos/python-test-shell-scripts',
        'how-tos/identify-git-outdated-files',
        'how-tos/code-driven-documentation',
        'how-tos/deploy-openapi-using-netlify',
        'how-tos/bundle-scripts-using-webpack',
        'how-tos/manage-python-project-using-poetry'
      ],
    }
  ],

};

module.exports = sidebars;
