/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  docs: [
    'intro',
    {
      type: 'category',
      label: 'My Reading List',
      link:{
        type: 'generated-index',
      },
      items: [
        'reading-list/git',
      ],
    },
    {
      type: 'category',
      label: 'Python',
      // Use link to generate index page for each category
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'category',
          label: 'Applied data science',
          link: {
            type: 'generated-index',
          },
          items:[
            'placeholder',
          ]
        },
        {
          type: 'category',
          label: 'Understanding and visualizing data',
          link: {
            type: 'generated-index',
          },
          items:[
            'placeholder',
          ]
        }
      ],
    },
    {
      type: 'category',
      label: 'Hadoop',
      link: {
        type: 'generated-index',
      },
      items: [
        'hadoop/hadoop-01-introduction',
        'hadoop/hadoop-02-about-mapreduce',
        'hadoop/hadoop-03-install-step-by-step'
      ],
    },
    {
      type: 'category',
      label: 'Game Theory',
      link: {
        type: 'generated-index',
      },
      items: [
        'placeholder'
      ],
    },
    {
      type: 'category',
      label: 'Docker',
      link: {
        type: 'generated-index',
      },
      items: [
        { type: 'ref', id: 'placeholder' }
      ],
    },
    {
      type: 'category',
      label: 'Linux',
      link: {
        type: 'generated-index',
      },
      items: [
        { type: 'ref', id: 'placeholder' }
      ],
    },
    {
      type: 'category',
      label: 'How-Tos',
      link: {
        type: 'generated-index',
      },
      items: [
        { type: 'ref', id: 'placeholder' }
      ],
    }
  ],

};

module.exports = sidebars;
