name: Crawler
on:
  workflow_dispatch:
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Algolia Crawler
        run: |
          docker run \
            -e "APPLICATION_ID=${{ secrets.ALGOLIA_APPLICATION_ID }}" \
            -e "API_KEY=${{ secrets.ALGOLIA_API_KEY }}" \
            -e "CONFIG=$(cat website/docsearch.json)" \
          algolia/docsearch-scraper
